spring:
  application:
    name: "umc9th" # "umc9th"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC ???? ??? ??
    url: ${DB_URL} # jdbc:mysql://localhost:3306/{???????}
    username: ${DB_USER} # MySQL ?? ??
    password: ${DB_PW} # MySQL ????

  jpa:
    database: mysql # ??? ?????? ?? ?? (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate?? ??? MySQL ??(dialect) ??
    show-sql: true # ??? SQL ??? ??? ???? ?? ??
    hibernate:
      ddl-auto: update # ?????? ?? ? ?????? ???? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? SQL ??? ?? ?? ???
        highlight_sql: true
        use_sql_comments: true

  logging:
    level:
      org.hibernate.SQL: DEBUG          # 실행된 SQL
      org.hibernate.orm.jdbc.bind: TRACE # 바인딩된 파라미터 (값까지 보기)
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE